[project]
name = "outlook-email-export"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "icecream>=2.1.4",
    "pandas>=2.2.3",
    "pydantic[email]>=2.11.4",
    "tabulate>=0.9.0",
]
